/**
 * Market Intelligence Service
 * Provides APMC Mandi benchmark rates, historical trends, and nearby mandi lookups.
 * Standardized around authoritative pricePerKg and derived pricePerQuintal (pricePerKg * 100).
 * 
 * DISCLAIMER: Powered by standardized agricultural benchmark data.
 * Architecture is prepared for official data source ingestion (AGMARKNET / e-NAM).
 */

const MANDI_DATA = [
  // Onion Mandis
  {
    id: 'mandi-pune-onion',
    marketName: 'Pune APMC Market Yard',
    name: 'Pune APMC Market Yard',
    district: 'Pune',
    state: 'Maharashtra',
    crop: 'Onion',
    cropCode: 'onion',
    variety: 'Red Onion / Garwa',
    pricePerKg: 18.4,
    pricePerQuintal: 1840,
    minPricePerQuintal: 1600,
    maxPricePerQuintal: 1980,
    changePercent: 5.1,
    change: '+5.1%',
    changeType: 'up',
    arrivalsQuintal: 1450,
    arrivals: '1,450 Q',
    status: 'High Demand',
    distanceKm: 45,
    lastUpdated: '2026-08-25T18:30:00Z',
  },
  {
    id: 'mandi-nashik-onion',
    marketName: 'Nashik APMC (Lasalgaon)',
    name: 'Nashik APMC (Lasalgaon)',
    district: 'Nashik',
    state: 'Maharashtra',
    crop: 'Onion',
    cropCode: 'onion',
    variety: 'Nashik Red',
    pricePerKg: 18.1,
    pricePerQuintal: 1810,
    minPricePerQuintal: 1550,
    maxPricePerQuintal: 1920,
    changePercent: 3.2,
    change: '+3.2%',
    changeType: 'up',
    arrivalsQuintal: 2800,
    arrivals: '2,800 Q',
    status: 'Moderate',
    distanceKm: 120,
    lastUpdated: '2026-08-25T18:30:00Z',
  },
  {
    id: 'mandi-mumbai-onion',
    marketName: 'Mumbai APMC (Vashi)',
    name: 'Mumbai APMC (Vashi)',
    district: 'Mumbai',
    state: 'Maharashtra',
    crop: 'Onion',
    cropCode: 'onion',
    variety: 'Export Garwa',
    pricePerKg: 19.5,
    pricePerQuintal: 1950,
    minPricePerQuintal: 1700,
    maxPricePerQuintal: 2100,
    changePercent: 1.8,
    change: '+1.8%',
    changeType: 'up',
    arrivalsQuintal: 3200,
    arrivals: '3,200 Q',
    status: 'High Demand',
    distanceKm: 180,
    lastUpdated: '2026-08-25T18:30:00Z',
  },
  {
    id: 'mandi-latur-onion',
    marketName: 'Latur APMC',
    name: 'Latur APMC',
    district: 'Latur',
    state: 'Maharashtra',
    crop: 'Onion',
    cropCode: 'onion',
    variety: 'Local Red',
    pricePerKg: 17.8,
    pricePerQuintal: 1780,
    minPricePerQuintal: 1500,
    maxPricePerQuintal: 1880,
    changePercent: -0.8,
    change: '-0.8%',
    changeType: 'down',
    arrivalsQuintal: 980,
    arrivals: '980 Q',
    status: 'Normal',
    distanceKm: 210,
    lastUpdated: '2026-08-25T18:30:00Z',
  },
  {
    id: 'mandi-solapur-onion',
    marketName: 'Solapur APMC',
    name: 'Solapur APMC',
    district: 'Solapur',
    state: 'Maharashtra',
    crop: 'Onion',
    cropCode: 'onion',
    variety: 'Red Onion',
    pricePerKg: 18.0,
    pricePerQuintal: 1800,
    minPricePerQuintal: 1550,
    maxPricePerQuintal: 1900,
    changePercent: 2.0,
    change: '+2.0%',
    changeType: 'up',
    arrivalsQuintal: 1120,
    arrivals: '1,120 Q',
    status: 'Active',
    distanceKm: 160,
    lastUpdated: '2026-08-25T18:30:00Z',
  },

  // Tomato Mandis
  {
    id: 'mandi-pune-tomato',
    marketName: 'Pune APMC Market Yard',
    name: 'Pune APMC Market Yard',
    district: 'Pune',
    state: 'Maharashtra',
    crop: 'Tomato',
    cropCode: 'tomato',
    variety: 'Hybrid Tomato',
    pricePerKg: 24.5,
    pricePerQuintal: 2450,
    minPricePerQuintal: 2100,
    maxPricePerQuintal: 2700,
    changePercent: 4.2,
    change: '+4.2%',
    changeType: 'up',
    arrivalsQuintal: 820,
    arrivals: '820 Q',
    status: 'High Demand',
    distanceKm: 45,
    lastUpdated: '2026-08-25T18:30:00Z',
  },
  {
    id: 'mandi-nashik-tomato',
    marketName: 'Nashik APMC (Dindori)',
    name: 'Nashik APMC (Dindori)',
    district: 'Nashik',
    state: 'Maharashtra',
    crop: 'Tomato',
    cropCode: 'tomato',
    variety: 'Desi / Local Red',
    pricePerKg: 23.8,
    pricePerQuintal: 2380,
    minPricePerQuintal: 2000,
    maxPricePerQuintal: 2600,
    changePercent: 3.5,
    change: '+3.5%',
    changeType: 'up',
    arrivalsQuintal: 1250,
    arrivals: '1,250 Q',
    status: 'Active',
    distanceKm: 110,
    lastUpdated: '2026-08-25T18:30:00Z',
  },
  {
    id: 'mandi-mumbai-tomato',
    marketName: 'Mumbai APMC (Vashi)',
    name: 'Mumbai APMC (Vashi)',
    district: 'Mumbai',
    state: 'Maharashtra',
    crop: 'Tomato',
    cropCode: 'tomato',
    variety: 'Grade A Table Tomato',
    pricePerKg: 26.0,
    pricePerQuintal: 2600,
    minPricePerQuintal: 2300,
    maxPricePerQuintal: 2900,
    changePercent: 2.1,
    change: '+2.1%',
    changeType: 'up',
    arrivalsQuintal: 1900,
    arrivals: '1,900 Q',
    status: 'High Demand',
    distanceKm: 180,
    lastUpdated: '2026-08-25T18:30:00Z',
  },

  // Potato Mandis
  {
    id: 'mandi-pune-potato',
    marketName: 'Pune APMC Market Yard',
    name: 'Pune APMC Market Yard',
    district: 'Pune',
    state: 'Maharashtra',
    crop: 'Potato',
    cropCode: 'potato',
    variety: 'Jyoti / Lokkar',
    pricePerKg: 21.0,
    pricePerQuintal: 2100,
    minPricePerQuintal: 1800,
    maxPricePerQuintal: 2300,
    changePercent: 1.4,
    change: '+1.4%',
    changeType: 'up',
    arrivalsQuintal: 1600,
    arrivals: '1,600 Q',
    status: 'Normal',
    distanceKm: 45,
    lastUpdated: '2026-08-25T18:30:00Z',
  },
  {
    id: 'mandi-manchar-potato',
    marketName: 'Manchar APMC',
    name: 'Manchar APMC',
    district: 'Pune',
    state: 'Maharashtra',
    crop: 'Potato',
    cropCode: 'potato',
    variety: 'Kufri Chipsona',
    pricePerKg: 22.5,
    pricePerQuintal: 2250,
    minPricePerQuintal: 1950,
    maxPricePerQuintal: 2450,
    changePercent: 3.8,
    change: '+3.8%',
    changeType: 'up',
    arrivalsQuintal: 850,
    arrivals: '850 Q',
    status: 'High Demand',
    distanceKm: 65,
    lastUpdated: '2026-08-25T18:30:00Z',
  },

  // Soybean Mandis
  {
    id: 'mandi-latur-soybean',
    marketName: 'Latur APMC',
    name: 'Latur APMC',
    district: 'Latur',
    state: 'Maharashtra',
    crop: 'Soybean',
    cropCode: 'soybean',
    variety: 'Yellow Soybean (JS 335)',
    pricePerKg: 48.5,
    pricePerQuintal: 4850,
    minPricePerQuintal: 4600,
    maxPricePerQuintal: 5100,
    changePercent: 1.5,
    change: '+1.5%',
    changeType: 'up',
    arrivalsQuintal: 2400,
    arrivals: '2,400 Q',
    status: 'Active',
    distanceKm: 210,
    lastUpdated: '2026-08-25T18:30:00Z',
  },
  {
    id: 'mandi-solapur-soybean',
    marketName: 'Solapur APMC',
    name: 'Solapur APMC',
    district: 'Solapur',
    state: 'Maharashtra',
    crop: 'Soybean',
    cropCode: 'soybean',
    variety: 'Yellow Grade A',
    pricePerKg: 48.0,
    pricePerQuintal: 4800,
    minPricePerQuintal: 4550,
    maxPricePerQuintal: 5000,
    changePercent: 0.9,
    change: '+0.9%',
    changeType: 'up',
    arrivalsQuintal: 1300,
    arrivals: '1,300 Q',
    status: 'Normal',
    distanceKm: 160,
    lastUpdated: '2026-08-25T18:30:00Z',
  },

  // Wheat Mandis
  {
    id: 'mandi-pune-wheat',
    marketName: 'Pune APMC Market Yard',
    name: 'Pune APMC Market Yard',
    district: 'Pune',
    state: 'Maharashtra',
    crop: 'Wheat',
    cropCode: 'wheat',
    variety: 'Sharbati / Lokwan',
    pricePerKg: 28.5,
    pricePerQuintal: 2850,
    minPricePerQuintal: 2600,
    maxPricePerQuintal: 3100,
    changePercent: 0.8,
    change: '+0.8%',
    changeType: 'up',
    arrivalsQuintal: 1100,
    arrivals: '1,100 Q',
    status: 'Stable',
    distanceKm: 45,
    lastUpdated: '2026-08-25T18:30:00Z',
  },
  {
    id: 'mandi-nashik-wheat',
    marketName: 'Nashik APMC',
    name: 'Nashik APMC',
    district: 'Nashik',
    state: 'Maharashtra',
    crop: 'Wheat',
    cropCode: 'wheat',
    variety: 'Lokwan Grade 1',
    pricePerKg: 27.8,
    pricePerQuintal: 2780,
    minPricePerQuintal: 2500,
    maxPricePerQuintal: 2950,
    changePercent: -0.4,
    change: '-0.4%',
    changeType: 'down',
    arrivalsQuintal: 950,
    arrivals: '950 Q',
    status: 'Normal',
    distanceKm: 120,
    lastUpdated: '2026-08-25T18:30:00Z',
  },

  // Cotton Mandis
  {
    id: 'mandi-jalna-cotton',
    marketName: 'Jalna APMC',
    name: 'Jalna APMC',
    district: 'Jalna',
    state: 'Maharashtra',
    crop: 'Cotton',
    cropCode: 'cotton',
    variety: 'Medium Staple Cotton',
    pricePerKg: 72.0,
    pricePerQuintal: 7200,
    minPricePerQuintal: 6800,
    maxPricePerQuintal: 7600,
    changePercent: 2.8,
    change: '+2.8%',
    changeType: 'up',
    arrivalsQuintal: 1800,
    arrivals: '1,800 Q',
    status: 'High Demand',
    distanceKm: 280,
    lastUpdated: '2026-08-25T18:30:00Z',
  },
];

const HISTORICAL_DATA = {
  onion: {
    '7d': [
      { date: '19 Aug', pricePerKg: 17.2, pricePerQuintal: 1720, arrivalsQuintal: 1200 },
      { date: '20 Aug', pricePerKg: 17.5, pricePerQuintal: 1750, arrivalsQuintal: 1300 },
      { date: '21 Aug', pricePerKg: 17.8, pricePerQuintal: 1780, arrivalsQuintal: 1380 },
      { date: '22 Aug', pricePerKg: 18.0, pricePerQuintal: 1800, arrivalsQuintal: 1400 },
      { date: '23 Aug', pricePerKg: 18.1, pricePerQuintal: 1810, arrivalsQuintal: 1420 },
      { date: '24 Aug', pricePerKg: 18.3, pricePerQuintal: 1830, arrivalsQuintal: 1440 },
      { date: '25 Aug', pricePerKg: 18.4, pricePerQuintal: 1840, arrivalsQuintal: 1450 },
    ],
    '30d': [
      { date: 'Week 1', pricePerKg: 16.5, pricePerQuintal: 1650, arrivalsQuintal: 4800 },
      { date: 'Week 2', pricePerKg: 17.1, pricePerQuintal: 1710, arrivalsQuintal: 5100 },
      { date: 'Week 3', pricePerKg: 17.8, pricePerQuintal: 1780, arrivalsQuintal: 5600 },
      { date: 'Week 4', pricePerKg: 18.4, pricePerQuintal: 1840, arrivalsQuintal: 5800 },
    ],
  },
  tomato: {
    '7d': [
      { date: '19 Aug', pricePerKg: 21.0, pricePerQuintal: 2100, arrivalsQuintal: 700 },
      { date: '20 Aug', pricePerKg: 22.0, pricePerQuintal: 2200, arrivalsQuintal: 720 },
      { date: '21 Aug', pricePerKg: 23.2, pricePerQuintal: 2320, arrivalsQuintal: 760 },
      { date: '22 Aug', pricePerKg: 23.8, pricePerQuintal: 2380, arrivalsQuintal: 790 },
      { date: '23 Aug', pricePerKg: 24.0, pricePerQuintal: 2400, arrivalsQuintal: 800 },
      { date: '24 Aug', pricePerKg: 24.2, pricePerQuintal: 2420, arrivalsQuintal: 810 },
      { date: '25 Aug', pricePerKg: 24.5, pricePerQuintal: 2450, arrivalsQuintal: 820 },
    ],
    '30d': [
      { date: 'Week 1', pricePerKg: 19.5, pricePerQuintal: 1950, arrivalsQuintal: 2800 },
      { date: 'Week 2', pricePerKg: 21.0, pricePerQuintal: 2100, arrivalsQuintal: 3000 },
      { date: 'Week 3', pricePerKg: 23.0, pricePerQuintal: 2300, arrivalsQuintal: 3200 },
      { date: 'Week 4', pricePerKg: 24.5, pricePerQuintal: 2450, arrivalsQuintal: 3250 },
    ],
  },
  potato: {
    '7d': [
      { date: '19 Aug', pricePerKg: 20.0, pricePerQuintal: 2000, arrivalsQuintal: 1400 },
      { date: '20 Aug', pricePerKg: 20.2, pricePerQuintal: 2020, arrivalsQuintal: 1450 },
      { date: '21 Aug', pricePerKg: 20.5, pricePerQuintal: 2050, arrivalsQuintal: 1500 },
      { date: '22 Aug', pricePerKg: 20.8, pricePerQuintal: 2080, arrivalsQuintal: 1550 },
      { date: '23 Aug', pricePerKg: 20.9, pricePerQuintal: 2090, arrivalsQuintal: 1580 },
      { date: '24 Aug', pricePerKg: 21.0, pricePerQuintal: 2100, arrivalsQuintal: 1600 },
      { date: '25 Aug', pricePerKg: 21.0, pricePerQuintal: 2100, arrivalsQuintal: 1600 },
    ],
    '30d': [
      { date: 'Week 1', pricePerKg: 19.0, pricePerQuintal: 1900, arrivalsQuintal: 5600 },
      { date: 'Week 2', pricePerKg: 19.8, pricePerQuintal: 1980, arrivalsQuintal: 5900 },
      { date: 'Week 3', pricePerKg: 20.5, pricePerQuintal: 2050, arrivalsQuintal: 6200 },
      { date: 'Week 4', pricePerKg: 21.0, pricePerQuintal: 2100, arrivalsQuintal: 6400 },
    ],
  },
  soybean: {
    '7d': [
      { date: '19 Aug', pricePerKg: 47.0, pricePerQuintal: 4700, arrivalsQuintal: 2100 },
      { date: '20 Aug', pricePerKg: 47.5, pricePerQuintal: 4750, arrivalsQuintal: 2150 },
      { date: '21 Aug', pricePerKg: 47.8, pricePerQuintal: 4780, arrivalsQuintal: 2200 },
      { date: '22 Aug', pricePerKg: 48.0, pricePerQuintal: 4800, arrivalsQuintal: 2250 },
      { date: '23 Aug', pricePerKg: 48.2, pricePerQuintal: 4820, arrivalsQuintal: 2300 },
      { date: '24 Aug', pricePerKg: 48.4, pricePerQuintal: 4840, arrivalsQuintal: 2350 },
      { date: '25 Aug', pricePerKg: 48.5, pricePerQuintal: 4850, arrivalsQuintal: 2400 },
    ],
    '30d': [
      { date: 'Week 1', pricePerKg: 46.0, pricePerQuintal: 4600, arrivalsQuintal: 8500 },
      { date: 'Week 2', pricePerKg: 46.8, pricePerQuintal: 4680, arrivalsQuintal: 8900 },
      { date: 'Week 3', pricePerKg: 47.5, pricePerQuintal: 4750, arrivalsQuintal: 9200 },
      { date: 'Week 4', pricePerKg: 48.5, pricePerQuintal: 4850, arrivalsQuintal: 9600 },
    ],
  },
  wheat: {
    '7d': [
      { date: '19 Aug', pricePerKg: 28.0, pricePerQuintal: 2800, arrivalsQuintal: 1000 },
      { date: '20 Aug', pricePerKg: 28.1, pricePerQuintal: 2810, arrivalsQuintal: 1020 },
      { date: '21 Aug', pricePerKg: 28.2, pricePerQuintal: 2820, arrivalsQuintal: 1050 },
      { date: '22 Aug', pricePerKg: 28.3, pricePerQuintal: 2830, arrivalsQuintal: 1060 },
      { date: '23 Aug', pricePerKg: 28.4, pricePerQuintal: 2840, arrivalsQuintal: 1080 },
      { date: '24 Aug', pricePerKg: 28.4, pricePerQuintal: 2840, arrivalsQuintal: 1090 },
      { date: '25 Aug', pricePerKg: 28.5, pricePerQuintal: 2850, arrivalsQuintal: 1100 },
    ],
    '30d': [
      { date: 'Week 1', pricePerKg: 27.5, pricePerQuintal: 2750, arrivalsQuintal: 4100 },
      { date: 'Week 2', pricePerKg: 27.8, pricePerQuintal: 2780, arrivalsQuintal: 4250 },
      { date: 'Week 3', pricePerKg: 28.2, pricePerQuintal: 2820, arrivalsQuintal: 4350 },
      { date: 'Week 4', pricePerKg: 28.5, pricePerQuintal: 2850, arrivalsQuintal: 4400 },
    ],
  },
  cotton: {
    '7d': [
      { date: '19 Aug', pricePerKg: 70.0, pricePerQuintal: 7000, arrivalsQuintal: 1500 },
      { date: '20 Aug', pricePerKg: 70.5, pricePerQuintal: 7050, arrivalsQuintal: 1550 },
      { date: '21 Aug', pricePerKg: 71.0, pricePerQuintal: 7100, arrivalsQuintal: 1620 },
      { date: '22 Aug', pricePerKg: 71.2, pricePerQuintal: 7120, arrivalsQuintal: 1680 },
      { date: '23 Aug', pricePerKg: 71.5, pricePerQuintal: 7150, arrivalsQuintal: 1720 },
      { date: '24 Aug', pricePerKg: 71.8, pricePerQuintal: 7180, arrivalsQuintal: 1760 },
      { date: '25 Aug', pricePerKg: 72.0, pricePerQuintal: 7200, arrivalsQuintal: 1800 },
    ],
    '30d': [
      { date: 'Week 1', pricePerKg: 68.0, pricePerQuintal: 6800, arrivalsQuintal: 6200 },
      { date: 'Week 2', pricePerKg: 69.5, pricePerQuintal: 6950, arrivalsQuintal: 6600 },
      { date: 'Week 3', pricePerKg: 70.8, pricePerQuintal: 7080, arrivalsQuintal: 7000 },
      { date: 'Week 4', pricePerKg: 72.0, pricePerQuintal: 7200, arrivalsQuintal: 7200 },
    ],
  },
};

export const marketService = {
  getPrices: (filters = {}) => {
    let result = [...MANDI_DATA];

    if (filters.crop) {
      const cropQuery = filters.crop.toLowerCase().trim();
      result = result.filter(
        (m) => m.cropCode === cropQuery || m.crop.toLowerCase().includes(cropQuery)
      );
    }

    if (filters.district) {
      const distQuery = filters.district.toLowerCase().trim();
      result = result.filter((m) => m.district.toLowerCase().includes(distQuery));
    }

    if (filters.market) {
      const marketQuery = filters.market.toLowerCase().trim();
      result = result.filter(
        (m) =>
          m.marketName.toLowerCase().includes(marketQuery) ||
          m.name.toLowerCase().includes(marketQuery)
      );
    }

    return result;
  },

  getHistory: (crop = 'onion', timeRange = '7d') => {
    const cropKey = crop.toLowerCase().trim();
    const cropHistory = HISTORICAL_DATA[cropKey] || HISTORICAL_DATA.onion;
    return cropHistory[timeRange] || cropHistory['7d'] || [];
  },

  getNearby: (lat, lng, maxDistance = 150) => {
    return [...MANDI_DATA]
      .filter((m) => (m.distanceKm || 0) <= maxDistance)
      .sort((a, b) => a.distanceKm - b.distanceKm);
  },
};
